const fs = require('fs');
let code = fs.readFileSync('app.js', 'utf8');

const newSignalingBlock = `// ============================================================================
// SERVERLESS WEBRTC SIGNALING PIPELINE (PEERJS GLOBAL RELAY)
// ============================================================================

let mySignalingPeer = null;
const signalingConns = {}; // Stores active PeerJS signaling connections

function initHostSignaling() {
    // Host registers on PeerJS cloud with the roomID
    mySignalingPeer = new Peer(\`privacz-\${roomID}\`);
    
    mySignalingPeer.on('open', () => {
        console.log('Host signaling active.');
    });

    mySignalingPeer.on('connection', (conn) => {
        // A guest connected for signaling
        signalingConns[conn.peer] = conn;
        
        conn.on('data', (data) => {
            handleSignalingData(data, conn.peer);
        });
        
        conn.on('close', () => {
            delete signalingConns[conn.peer];
        });
    });
}

function initGuestSignaling() {
    const statusEl = document.getElementById('guest-status');
    if (statusEl) statusEl.innerText = 'Locating Host on Global Relay...';
    
    // Guest registers with a random ID
    mySignalingPeer = new Peer();
    
    mySignalingPeer.on('open', (id) => {
        if (statusEl) statusEl.innerText = 'Binding WebRTC channels...';
        
        // Connect to the Host's room ID
        const conn = mySignalingPeer.connect(\`privacz-\${roomID}\`);
        
        conn.on('open', () => {
            signalingConns['host'] = conn;
            // Send join packet to host
            sendSignaling({
                type: 'join',
                from: myId,
                color: myColor
            });
        });
        
        conn.on('data', (data) => {
            handleSignalingData(data, 'host');
        });
        
        conn.on('close', () => {
            delete signalingConns['host'];
        });
    });
    
    mySignalingPeer.on('error', (err) => {
        if (statusEl) statusEl.innerText = 'Connection failed. Host might be offline.';
        console.error('Signaling Error:', err);
    });
}

function sendSignaling(data) {
    if (isHost) {
        // If we specify 'to', send only to that guest, otherwise broadcast
        if (data.to && signalingConns[data.to]) {
            signalingConns[data.to].send(data);
        } else {
            Object.values(signalingConns).forEach(conn => {
                if (conn.open) conn.send(data);
            });
        }
    } else {
        // Guest sends to host
        if (signalingConns['host'] && signalingConns['host'].open) {
            signalingConns['host'].send(data);
        }
    }
}

function broadcast(msg) {
    const payload = typeof msg === 'string' ? msg : JSON.stringify(msg);
    Object.values(peers).forEach(peer => {
        if (peer.dc && peer.dc.readyState === 'open') {
            try { peer.dc.send(payload); } catch(e) {}
        }
    });
}

function sendToHost(msg) {
    broadcast(msg);
}

async function handleSignalingData(data, sourcePeerId) {
    if (!data || data.from === myId) return;

    try {
        if (isHost) {
            if (data.type === 'join') {
                const guestId = data.from;
                // Save the source PeerJS ID so we know where to route messages for this guestId
                // The 'guestId' is the myId generated by the guest (which is what we use in peers mapping)
                // We map guestId to the peerjs connection id
                const peerjsConnId = sourcePeerId; 
                signalingConns[guestId] = signalingConns[peerjsConnId];
                
                if (!peers[guestId]) {
                    peers[guestId] = createPeer(guestId, data.color);
                    const dc = peers[guestId].pc.createDataChannel('privacz');
                    setupDataChannel(dc, guestId);
                    peers[guestId].dc = dc;

                    const offer = await peers[guestId].pc.createOffer();
                    await peers[guestId].pc.setLocalDescription(offer);
                    sendSignaling({
                        type: 'offer',
                        sdp: offer,
                        from: myId,
                        to: guestId,
                        hostColor: myColor
                    });
                }
            }
            if (data.type === 'answer' && data.to === myId && peers[data.from]) {
                await peers[data.from].pc.setRemoteDescription(new RTCSessionDescription(data.sdp));
                updatePresence();
            }
            if (data.type === 'candidate' && data.to === myId && peers[data.from]) {
                await peers[data.from].pc.addIceCandidate(new RTCIceCandidate(data.candidate));
            }
        } else {
            if (data.type === 'offer' && data.to === myId) {
                const hostId = data.from;
                if (!peers[hostId]) {
                    peers[hostId] = createPeer(hostId, data.hostColor || 'Host');
                    peers[hostId].pc.ondatachannel = (event) => {
                        peers[hostId].dc = event.channel;
                        setupDataChannel(event.channel, hostId);
                    };
                }
                await peers[hostId].pc.setRemoteDescription(new RTCSessionDescription(data.sdp));
                const answer = await peers[hostId].pc.createAnswer();
                await peers[hostId].pc.setLocalDescription(answer);
                sendSignaling({
                    type: 'answer',
                    sdp: answer,
                    from: myId,
                    to: hostId
                });
            }
            if (data.type === 'candidate' && data.to === myId && peers[data.from]) {
                await peers[data.from].pc.addIceCandidate(new RTCIceCandidate(data.candidate));
            }
        }
    } catch (err) {
        console.warn("Signaling notification:", err);
    }
}
`;

const oldBlockRegex = /\/\/ ============================================================================\n\/\/ SERVERLESS WEBRTC SIGNALING PIPELINE[\s\S]*?console\.warn\("Signaling notification:", err\);\n    \}\n\}\);/m;

code = code.replace(oldBlockRegex, newSignalingBlock);

// Replace initHostSignaling hook in openHostSetup and openFileTransferModalHost
code = code.replace(
    /roomID = Math\.random\(\)\.toString\(36\)\.substring\(2, 10\);\n    document\.getElementById\('modal-host-setup'\)/g,
    `roomID = Math.random().toString(36).substring(2, 10);\n    initHostSignaling();\n    document.getElementById('modal-host-setup')`
);

code = code.replace(
    /roomID = Math\.random\(\)\.toString\(36\)\.substring\(2, 10\);\n    const modal = document\.getElementById\('modal-file-transfer'\);/g,
    `roomID = Math.random().toString(36).substring(2, 10);\n    initHostSignaling();\n    const modal = document.getElementById('modal-file-transfer');`
);

// Replace localStorage candidate emitting in createPeer
code = code.replace(
    /localStorage\.setItem\(\`privacz_\$\{roomID\}_candidate_\$\{myId\}_\$\{Date\.now\(\)\}\`, JSON\.stringify\(\{\n                type: 'candidate',\n                candidate: event\.candidate,\n                from: myId,\n                to: id\n            \}\)\);/g,
    `sendSignaling({\n                type: 'candidate',\n                candidate: event.candidate,\n                from: myId,\n                to: id\n            });`
);


fs.writeFileSync('app.js', code);
